credentials:
  username: ""
  password: ""

daemon:
  min-likes-x-photo: 20
  - tags:
      - "triumph"
      - ""
    hour: "22:00"
    likes: 60
  - tags:
      - "triumph"
      - ""
    hour: "22:00"
    likes: 60
  - tags:
      - "triumph"
      - ""
    hour: "22:00"
    likes: 60
  - tags:
      - "triumph"
      - ""
    hour: "22:00"
    likes: 60
